services:
  - type: web
    name: sigpac-sentinel-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: COPERNICUS_USER
        sync: false
      - key: COPERNICUS_PASS
        sync: false
    disk:
      name: cache-disk
      mountPath: /opt/render/project/src/cache
      sizeGB: 1
